name: UpdateDocs

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [update_docs]
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0 
          ref: 'main'

      - name: sync docs source
        run: |
          git submodule update --remote --rebase docs

      - name: build docs
        run: |
          pip install mkdocs-material
          mkdocs build

      - name: sync to server
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -rv --delete
          path: site/
          remote_path: /home/wiki/wiki.sast.fun/
          remote_host: wiki.sast.fun
          remote_user: wiki
          remote_key: ${{ secrets.DEPLOY_KEY }}


